// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuthStatus = { authenticated: boolean, 
/**
 * False when no password is configured — the UI explains the fix rather
 * than showing a login form that cannot succeed.
 */
configured: boolean, };

/**
 * A directory that looks like it holds a camera's clips.
 *
 * Candidates are identified by evidence — date-shaped subdirectories and
 * video files — rather than by excluding a hardcoded list of known
 * non-camera directory names, which would only ever match one user's layout.
 */
export type CameraCandidate = { dir_name: string, 
/**
 * Subdirectories shaped like `YYYY-MM-DD`.
 */
date_dirs: number, clip_count: number, 
/**
 * Whether we would pre-select this one.
 */
looks_like_camera: boolean, note: string | null, };

export type CameraInfo = { camera_id: string, 
/**
 * Name derived from the clip path.
 */
derived_name: string | null, 
/**
 * What to show. Falls back to the derived name, then the raw id.
 */
display_name: string, event_count: number, 
/**
 * Unix seconds of the most recent event, if any.
 */
last_event: number | null, };

export type Check = { ok: boolean, detail: string, };

/**
 * Where a clip's bytes are, which is not the same as whether an event exists.
 */
export type ClipStatus = "Live" | "Archived" | "Vanished" | "PendingBackfill" | "NeverBackedUp";

export type ContainerRef = { id: string, name: string, image: string, state: string | null, };

export type DiscoveryResult = { containers: Array<ContainerRef>, inspection: UpbInspection | null, cameras: Array<CameraCandidate>, notes: Array<string>, };

export type EventPage = { events: Array<EventRecord>, 
/**
 * Total matching the filter, for pagination.
 */
total: number, offset: number, limit: number, };

export type EventQuery = { camera_id?: string, event_type?: string, subtype?: string, status?: ClipStatus, from?: number, to?: number, limit?: number | null, offset?: number | null, };

export type EventRecord = { id: string, camera_id: string, 
/**
 * Resolved display name, falling back to the raw id when unknown.
 */
camera: string, 
/**
 * The backup service's own event type, e.g. `smartDetectZone`.
 */
event_type: string, 
/**
 * Detection types, which live in the clip's filename rather than the
 * database, and can be multiple for one event.
 */
subtypes: Array<string>, 
/**
 * Unix seconds.
 */
start: number, end: number, duration: number, status: ClipStatus, 
/**
 * Path as this container would open it. Absent when never backed up.
 */
clip_path: string | null, size_bytes: number, };

export type Health = { ok: boolean, docker: Check, container: Check, backup_dir: Check, 
/**
 * Things that are wrong and need attention.
 */
warnings: Array<string>, 
/**
 * Things worth stating that are not, by themselves, problems. Kept
 * separate so the warning list stays meaningful when it is non-empty.
 */
info: Array<string>, };

/**
 * Health of the index itself, and of the backup pipeline feeding it.
 */
export type IndexStats = { total_events: number, live_clips: number, archived: number, vanished: number, pending_backfill: number, never_backed_up: number, 
/**
 * Seconds since the newest event that has a clip — the single best
 * "is the pipeline working" signal, and free to compute.
 */
backup_lag_secs: number | null, newest_event: number | null, oldest_event: number | null, 
/**
 * When the index last synced, and whether that attempt worked.
 */
last_sync: number | null, last_sync_error: string | null, distinct_subtypes: Array<string>, };

export type LoginRequest = { password: string, };

export type MountInfo = { source: string | null, destination: string, rw: boolean, };

export type NamedCheck = { name: string, ok: boolean, detail: string, };

/**
 * Configuration proposed from the backup container itself, so setup is a
 * confirmation rather than a typing exercise.
 */
export type ProposedConfig = { sqlite_container_path: string | null, sqlite_host_path: string | null, backup_host_dir: string | null, 
/**
 * Prefix to strip from `backups.path` when resolving a clip.
 */
clip_path_prefix: string | null, 
/**
 * Where the database lands inside *our* mount — the only form we can open.
 */
events_db_local_path: string | null, 
/**
 * Why any of the above is missing, in words the user can act on.
 */
notes: Array<string>, };

export type Settings = { upb_container_id: string | null, 
/**
 * `events.sqlite` as *this* container can open it.
 */
events_db_path: string | null, 
/**
 * Prefix to strip from `backups.path`.
 */
clip_path_prefix: string | null, 
/**
 * Camera directories the user confirmed.
 */
camera_dirs: Array<string>, 
/**
 * How long clips stay viewable. The same number decides when they are
 * archived — one knob, phrased the way the user thinks about it.
 */
live_window_months: number, setup_complete: boolean, };

export type SetupState = { settings: Settings, 
/**
 * Whether enough is configured for the app to do anything useful.
 */
complete: boolean, 
/**
 * Validation of the current settings, re-run on each request so a path
 * that disappears is noticed rather than remembered as good.
 */
checks: Array<NamedCheck>, };

export type UpbInspection = { container: ContainerRef, running: boolean, started_at: string | null, restart_count: number, 
/**
 * Docker health is unavailable when the container disables its
 * healthcheck, which the backup service's image does by default.
 */
health_available: boolean, mounts: Array<MountInfo>, 
/**
 * Only an allowlist is read; the container's environment holds NVR
 * credentials in plaintext.
 */
env: Array<[string, string]>, env_withheld: number, command: string | null, retention: string | null, missing_range: string | null, proposed: ProposedConfig, };
