// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An archive on disk, as far as we know it.
 */
export type ArchiveEntry = { camera: string, month: string, path: string, size_bytes: number, file_count: number, created: number | null, verified_at: number | null, verify_ok: boolean | null, 
/**
 * Restored back to live, so the scheduler must leave it alone until
 * released — otherwise the next run would immediately re-archive it.
 */
pinned: boolean, 
/**
 * On disk but with no run history: made by hand, or by whatever managed
 * archiving before this app did.
 */
unrecorded: boolean, };

export type ArchiveOverview = { archives: Array<ArchiveEntry>, due: Array<DueEntry>, 
/**
 * Runs whose archive is no longer on disk.
 */
missing_archives: Array<CameraMonth>, total_bytes: number, running: ArchiveRun | null, };

export type ArchiveRun = { id: number, kind: RunKind, status: RunStatus, 
/**
 * Absent for a run that covered several camera-months.
 */
camera: string | null, month: string | null, started: number, finished: number | null, 
/**
 * True when nothing was written or deleted.
 */
dry_run: boolean, 
/**
 * Whether a schedule started this, rather than a person.
 */
scheduled: boolean, files_total: number, files_done: number, bytes_total: number, message: string | null, 
/**
 * Files whose content did not survive the round trip. Empty on success,
 * and the reason sources are still on disk when it isn't.
 */
failed_files: Array<string>, };

export type AuthStatus = { authenticated: boolean, 
/**
 * False when no password is configured — the UI explains the fix rather
 * than showing a login form that cannot succeed.
 */
configured: boolean, };

/**
 * A directory that looks like it holds a camera's clips.
 *
 * Candidates are identified by evidence — date-shaped subdirectories and
 * video files — rather than by excluding a hardcoded list of known
 * non-camera directory names, which would only ever match one user's layout.
 */
export type CameraCandidate = { dir_name: string, 
/**
 * Subdirectories shaped like `YYYY-MM-DD`.
 */
date_dirs: number, clip_count: number, 
/**
 * Whether we would pre-select this one.
 */
looks_like_camera: boolean, note: string | null, };

export type CameraInfo = { camera_id: string, 
/**
 * Name derived from the clip path.
 */
derived_name: string | null, 
/**
 * What to show. Falls back to the derived name, then the raw id.
 */
display_name: string, event_count: number, 
/**
 * Unix seconds of the most recent event, if any.
 */
last_event: number | null, };

/**
 * A camera-month: the unit everything here operates on, because archives are
 * one tar per camera per calendar month.
 */
export type CameraMonth = { camera: string, 
/**
 * `YYYY-MM`.
 */
month: string, };

export type CameraUsage = { camera: string, live_bytes: number, archive_bytes: number, live_clips: number, archived_months: number, };

export type Check = { ok: boolean, detail: string, };

/**
 * What playing a clip will involve, so the UI can be honest about a wait.
 */
export type ClipInfo = { id: string, available: boolean, 
/**
 * Why it isn't, when it isn't.
 */
reason: string | null, codec: string | null, width: number | null, height: number | null, 
/**
 * Size of the recording itself, not of any transcode.
 */
size_bytes: number | null, 
/**
 * Frames per second, so stepping a frame steps exactly one frame rather
 * than an assumed fraction of a second.
 */
fps: number | null, 
/**
 * True when the browser can play the recording as-is.
 */
direct: boolean, 
/**
 * True when a transcode already exists, so playback starts immediately.
 */
prepared: boolean, };

/**
 * Where a clip's bytes are, which is not the same as whether an event exists.
 */
export type ClipStatus = "Live" | "Archived" | "Vanished" | "PendingBackfill" | "NeverBackedUp";

export type ContainerRef = { id: string, name: string, image: string, state: string | null, };

export type DiscoveryResult = { containers: Array<ContainerRef>, inspection: UpbInspection | null, cameras: Array<CameraCandidate>, notes: Array<string>, };

/**
 * A camera-month old enough to archive that hasn't been.
 */
export type DueEntry = { camera: string, month: string, file_count: number, bytes: number, 
/**
 * Why it hasn't been archived, when the answer isn't "not yet".
 */
blocked: string | null, };

export type EventPage = { events: Array<EventRecord>, 
/**
 * Total matching the filter, for pagination.
 */
total: number, offset: number, limit: number, };

export type EventQuery = { camera_id?: string, event_type?: string, subtype?: string, status?: ClipStatus, from?: number, to?: number, limit?: number | null, offset?: number | null, };

export type EventRecord = { id: string, camera_id: string, 
/**
 * Resolved display name, falling back to the raw id when unknown.
 */
camera: string, 
/**
 * The backup service's own event type, e.g. `smartDetectZone`.
 */
event_type: string, 
/**
 * Detection types, which live in the clip's filename rather than the
 * database, and can be multiple for one event.
 */
subtypes: Array<string>, 
/**
 * Unix seconds.
 */
start: number, end: number, duration: number, status: ClipStatus, 
/**
 * Path as this container would open it. Absent when never backed up.
 */
clip_path: string | null, size_bytes: number, };

/**
 * Usage of one filesystem, as the kernel reports it.
 */
export type FilesystemUsage = { 
/**
 * The path we asked about, as mounted in this container.
 */
path: string, total_bytes: number, free_bytes: number, 
/**
 * Device id, so two paths on the same filesystem can be recognised as one
 * — otherwise their free space looks like twice what exists.
 */
device: number, };

export type Health = { ok: boolean, docker: Check, container: Check, backup_dir: Check, 
/**
 * Things that are wrong and need attention.
 */
warnings: Array<string>, 
/**
 * Things worth stating that are not, by themselves, problems. Kept
 * separate so the warning list stays meaningful when it is non-empty.
 */
info: Array<string>, };

/**
 * Health of the index itself, and of the backup pipeline feeding it.
 */
export type IndexStats = { total_events: number, live_clips: number, archived: number, vanished: number, pending_backfill: number, never_backed_up: number, 
/**
 * Seconds since the newest event that has a clip — the single best
 * "is the pipeline working" signal, and free to compute.
 */
backup_lag_secs: number | null, newest_event: number | null, oldest_event: number | null, 
/**
 * When the index last synced, and whether that attempt worked.
 */
last_sync: number | null, last_sync_error: string | null, distinct_subtypes: Array<string>, };

export type LoginRequest = { password: string, };

export type MountInfo = { source: string | null, destination: string, rw: boolean, };

export type NamedCheck = { name: string, ok: boolean, detail: string, };

/**
 * Configuration proposed from the backup container itself, so setup is a
 * confirmation rather than a typing exercise.
 */
export type ProposedConfig = { sqlite_container_path: string | null, sqlite_host_path: string | null, backup_host_dir: string | null, 
/**
 * Prefix to strip from `backups.path` when resolving a clip.
 */
clip_path_prefix: string | null, 
/**
 * Where the database lands inside *our* mount — the only form we can open.
 */
events_db_local_path: string | null, 
/**
 * Why any of the above is missing, in words the user can act on.
 */
notes: Array<string>, };

export type RunKind = "Archive" | "Restore" | "Verify";

/**
 * Live progress for a running job.
 */
export type RunProgress = { run_id: number, kind: RunKind, 
/**
 * What is being worked on right now.
 */
camera: string | null, month: string | null, phase: string, current_file: string | null, 
/**
 * Progress through the current camera-month.
 */
files_done: number, files_total: number, 
/**
 * Progress across the whole run, which may span several camera-months.
 */
overall_done: number, overall_total: number, finished: boolean, status: RunStatus | null, message: string | null, };

export type RunStatus = "Running" | "Succeeded" | "Failed" | "Interrupted";

export type Schedule = { kind: ScheduleKind, 
/**
 * Day of month for `Monthly`, ignored otherwise.
 */
day: number, 
/**
 * Local hour, 0–23.
 */
hour: number, 
/**
 * Run as soon as the app starts if the scheduled time was missed while it
 * was down. A late archive beats a skipped one.
 */
catch_up: boolean, 
/**
 * Optional POST on failure, so a silent failure can't hide behind a
 * closed browser tab.
 */
webhook_url: string | null, next_run: number | null, last_run: number | null, };

export type ScheduleKind = "Off" | "Monthly" | "Daily";

export type Settings = { upb_container_id: string | null, 
/**
 * `events.sqlite` as *this* container can open it.
 */
events_db_path: string | null, 
/**
 * Prefix to strip from `backups.path`.
 */
clip_path_prefix: string | null, 
/**
 * Camera directories the user confirmed.
 */
camera_dirs: Array<string>, 
/**
 * How long clips stay viewable. The same number decides when they are
 * archived — one knob, phrased the way the user thinks about it.
 */
live_window_months: number, 
/**
 * Keep the originals after an archive verifies clean.
 *
 * Defaults to false — the sources are removed — because the backup
 * service never deletes anything itself, so nothing else on the system
 * bounds disk growth. Turning this on means the live directory grows
 * forever, which is a legitimate choice but has to be a deliberate one.
 */
keep_sources_after_archive: boolean, setup_complete: boolean, };

export type SetupState = { settings: Settings, 
/**
 * Whether enough is configured for the app to do anything useful.
 */
complete: boolean, 
/**
 * Validation of the current settings, re-run on each request so a path
 * that disappears is noticed rather than remembered as good.
 */
checks: Array<NamedCheck>, };

export type StartArchiveRequest = { 
/**
 * Empty means everything currently due.
 */
targets: Array<CameraMonth>, 
/**
 * Report what would happen, writing and deleting nothing.
 */
dry_run: boolean, };

export type StorageSample = { at: number, live_bytes: number, archive_bytes: number, free_bytes: number, };

export type StorageSnapshot = { backup: FilesystemUsage | null, archive: FilesystemUsage | null, 
/**
 * True when both directories live on the same filesystem, which changes
 * what "free space" means for archiving: packing then deleting frees
 * nothing until the sources go.
 */
same_filesystem: boolean, live_bytes: number, archive_bytes: number, cameras: Array<CameraUsage>, 
/**
 * Bytes per day, measured over the sampled history. `None` until there
 * is enough history to say anything honest.
 */
growth_bytes_per_day: number | null, 
/**
 * Days until the fuller of the two filesystems runs out at that rate.
 */
days_until_full: number | null, };

export type UpbInspection = { container: ContainerRef, running: boolean, started_at: string | null, restart_count: number, 
/**
 * Docker health is unavailable when the container disables its
 * healthcheck, which the backup service's image does by default.
 */
health_available: boolean, mounts: Array<MountInfo>, 
/**
 * Only an allowlist is read; the container's environment holds NVR
 * credentials in plaintext.
 */
env: Array<[string, string]>, env_withheld: number, command: string | null, retention: string | null, missing_range: string | null, proposed: ProposedConfig, };

export type WatchdogConfig = { 
/**
 * Watch for the backup service recording events but not downloading them.
 */
enabled: boolean, 
/**
 * How long the symptom must persist before it counts. Clips are fetched
 * a little after the event ends, so a brief gap is normal.
 */
grace_minutes: number, 
/**
 * Restart the backup container when a stall is confirmed.
 *
 * Off by default: restarting someone else's container is a deliberate
 * choice, and the detector should earn trust on a given setup first.
 */
auto_restart: boolean, 
/**
 * Minimum time between automatic restarts, so a service that is broken
 * for another reason is not restarted in a loop.
 */
restart_cooldown_minutes: number, 
/**
 * Where to POST when a stall is detected. Falls back to the archive
 * schedule's webhook when empty, so there is one place to configure it.
 */
webhook_url: string | null, };

export type WatchdogEvent = { at: number, 
/**
 * `detected`, `restarted`, `notified`, `recovered`, or `failed`.
 */
action: string, detail: string, };

/**
 * What the watchdog currently believes, and why.
 */
export type WatchdogState = { config: WatchdogConfig, stalled: boolean, 
/**
 * When the symptom was first seen, if it is present now.
 */
stalled_since: number | null, 
/**
 * Newest event the backup service has *recorded*.
 */
newest_event: number | null, 
/**
 * Newest event it has actually *downloaded*.
 */
newest_captured: number | null, 
/**
 * Seconds between those two — the measure the detector uses.
 */
gap_secs: number | null, 
/**
 * Events recorded since the last successful download.
 */
uncaptured: number, 
/**
 * Plain-language reading of the two numbers above.
 */
summary: string, last_restart: number | null, log: Array<WatchdogEvent>, };
